CREATE TABLE polls (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  uuid UUID NOT NULL,
  start_time TIMESTAMPTZ DEFAULT now(),
  end_time TIMESTAMPTZ DEFAULT now() + interval '5 minutes',
  city TEXT,
  zip INTEGER
);
CREATE TABLE resturants (
poll_id INTEGER REFERENCES polls(id) NOT NULL,
id INTEGER,
name TEXT,
address TEXT,
city TEXT,
postal_code TEXT,
country TEXT,
phone TEXT,
lat INTEGER,
lng INTEGER, 
reserve_url TEXT,
mobile_reserve_url TEXT,
image_url TEXT
);

CREATE TABLE votes (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  poll_id INTEGER REFERENCES polls(id) NOT NULL,
  restaurant_id INTEGER NOT NULL,
  created_time TIMESTAMPTZ DEFAULT now(),
  user_ip TEXT 
);