CREATE TABLE polls (
  uuid UUID NOT NULL PRIMARY KEY,
  start_time TIMESTAMPTZ DEFAULT now(),
  end_time TIMESTAMPTZ DEFAULT now() + interval '5 minutes',
  city TEXT,
  postal_code INTEGER
);



CREATE TABLE restaurants (
_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
poll_id UUID REFERENCES polls(uuid) NOT NULL,
id INTEGER,
name TEXT,
address TEXT,
city TEXT,
state TEXT,
area TEXT,
postal_code TEXT,
country TEXT,
phone TEXT,
lat NUMERIC,
lng NUMERIC,
price INTEGER, 
reserve_url TEXT,
mobile_reserve_url TEXT,
image_url TEXT
);

CREATE TABLE votes (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  poll_id UUID REFERENCES polls(uuid) NOT NULL,
  restaurant_id INTEGER NOT NULL,
  created_time TIMESTAMPTZ DEFAULT now(),
  user_ip TEXT 
);